FROM node:22

WORKDIR /app

COPY .  ./
RUN npm install -g @angular/cli
RUN npm install
# 
RUN ng b @space-truckers/client --configuration=production

EXPOSE 4200
CMD ["ng", "serve","--proxy-config=packages/client/proxy.conf.prod.json", "--host=0.0.0.0"]
