FROM node:22

WORKDIR /app

COPY .  ./

RUN npm install -g @angular/cli
RUN npm install
RUN ng b @space-truckers/types
RUN ng b @space-truckers/common
EXPOSE 8080

CMD [ "npm", "run" ,"watch", "-w=@space-truckers/api" ]
